package com.vectorsf.jvoiceframework.testapp.locution;
import ch.qos.cal10n.BaseName;
import ch.qos.cal10n.Locale;
import ch.qos.cal10n.LocaleData;

@BaseName("com.vectorsf.jvoiceframework.testapp.locution.Login")
@LocaleData(defaultCharset="UTF8", value={@Locale(value="es_ES", charset="ISO8859_1"), @Locale(value="en_US")})
public enum Login {
	LOGIN_IDENTIFICATION_PT1,
	LOGIN_IDENTIFICATION_PT2,
	LOGIN_IDENTIFICATION_PT3,
	LOGIN_IDENTIFICATION_NI_PT1,
	LOGIN_IDENTIFICATION_NI_PT2,
	LOGIN_IDENTIFICATION_NI_PT3,
	LOGIN_IDENTIFICATION_NM_PT1,
	LOGIN_IDENTIFICATION_NM_PT2,
	LOGIN_IDENTIFICATION_NM_PT3,
	LOGIN_AUTHENTICATION_PT1,
	LOGIN_AUTHENTICATION_PT2,
	LOGIN_AUTHENTICATION_PT3,
	LOGIN_AUTHENTICATION_NI_PT1,
	LOGIN_AUTHENTICATION_NI_PT2,
	LOGIN_AUTHENTICATION_NI_PT3,
	LOGIN_AUTHENTICATION_NM_PT1,
	LOGIN_AUTHENTICATION_NM_PT2,
	LOGIN_AUTHENTICATION_NM_PT3,
	ERROR;
}
