//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.02 at 12:23:36 PM CEST 
//


package org.isb.ivr.flow.webservices.jaxbbeans.binding;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jvoice.webservices.jaxbbean.v3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EXNoAccount_QNAME = new QName("urn:WSDLTemplates", "EXNoAccount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jvoice.webservices.jaxbbean.v3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Op1Response }
     * 
     */
    public Op1Response createOp1Response() {
        return new Op1Response();
    }

    /**
     * Create an instance of {@link Op1 }
     * 
     */
    public Op1 createOp1() {
        return new Op1();
    }

    /**
     * Create an instance of {@link EXNoAccount }
     * 
     */
    public EXNoAccount createEXNoAccount() {
        return new EXNoAccount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EXNoAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:WSDLTemplates", name = "EXNoAccount")
    public JAXBElement<EXNoAccount> createEXNoAccount(EXNoAccount value) {
        return new JAXBElement<EXNoAccount>(_EXNoAccount_QNAME, EXNoAccount.class, null, value);
    }

}
