
package com.vectorsf.jvoiceframework.ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://bluedash.net/ws", wsdlLocation = "http://localhost/wsdl/hello.wsdl")
public class HelloService_Service
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.vectorsf.jvoiceframework.ws.test.HelloService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.vectorsf.jvoiceframework.ws.test.HelloService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/wsdl/hello.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/wsdl/hello.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService_Service() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://bluedash.net/ws", "HelloService"));
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceSOAP")
    public HelloService getHelloServiceSOAP() {
        return super.getPort(new QName("http://bluedash.net/ws", "HelloServiceSOAP"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceSOAP")
    public HelloService getHelloServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://bluedash.net/ws", "HelloServiceSOAP"), HelloService.class, features);
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "OtherHelloServiceSOAP")
    public HelloService getOtherHelloServiceSOAP() {
        return super.getPort(new QName("http://bluedash.net/ws", "OtherHelloServiceSOAP"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "OtherHelloServiceSOAP")
    public HelloService getOtherHelloServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://bluedash.net/ws", "OtherHelloServiceSOAP"), HelloService.class, features);
    }

}
